# Generated by Django 4.2.2 on 2023-08-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoryproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryProducts',
        ),
    ]
