# Generated by Django 4.2.2 on 2023-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_categoryproducts_categoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='trekking_route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
