# Generated by Django 4.2.2 on 2023-08-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categoryproduct_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoryProduct',
            new_name='categoryTravel',
        ),
    ]
