# Generated by Django 4.2.2 on 2023-08-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_categoryproduct_categorytravel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoryTravel',
            new_name='categoryProduct',
        ),
    ]
