# Generated by Django 4.2.2 on 2023-08-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_categorytravel_categoryproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryProduct',
        ),
    ]
